import assert from 'node:assert/strict';
import {transcribeVoice} from './voice.mjs';
const voice={file_id:'file',duration:10,file_size:8};
const env=n=>({TOCHKA_ASSISTANT_TRANSCRIBE_URL:'https://voice.example.workers.dev',TOCHKA_ASSISTANT_TRANSCRIBE_SECRET:'a'.repeat(32),TOCHKA_ASSISTANT_BOT_TOKEN:'fake-token'})[n];
let calls=[];
const tg=async()=>({file_path:'voice/file_1.oga',file_size:8});
const request=async(url,o)=>{calls.push(url);if(url.includes('/file/bot'))return new Response('OggSfake',{headers:{'content-type':'audio/ogg'}});assert.equal(url,'https://voice.example.workers.dev');assert.equal(o.headers['x-tochka-transcribe-secret'],'a'.repeat(32));assert.ok(o.body instanceof Blob);return Response.json({text:'Завтра в 18:00 встреча',segments:[{no_speech_prob:0.01}]});};
assert.equal(await transcribeVoice({voice,env,tg,request}),'Завтра в 18:00 встреча');
assert.equal(calls.length,2);
await assert.rejects(transcribeVoice({voice,env:()=>undefined,tg,request}),/voice_not_configured/);
await assert.rejects(transcribeVoice({voice:{...voice,duration:61},env,tg,request}),/voice_too_long/);
await assert.rejects(transcribeVoice({voice:{...voice,file_size:5e6},env,tg,request}),/voice_too_large/);
await assert.rejects(transcribeVoice({voice,env,tg:async()=>({file_path:'../secrets'}),request}),/voice_empty/);
await assert.rejects(transcribeVoice({voice,env,tg,request:async url=>url.includes('/file/bot')?new Response('audio'):Response.json({text:'Спасибо за просмотр',segments:[{no_speech_prob:0.95}]})}),/voice_empty/);
await assert.rejects(transcribeVoice({voice,env,tg,request:async url=>url.includes('/file/bot')?new Response('audio'):new Response('',{status:401})}),/voice_key/);
await assert.rejects(transcribeVoice({voice,env,tg,request:async()=>new Response(new Uint8Array(4*1024*1024+1))}),/voice_too_large/);
console.log('PASS voice upload, format, Russian, missing key, duration/size, path safety, silence, provider failure, streamed size');
