const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
(async()=>{
 const {dueEvents}=await import('./supabase/functions/push/schedule.js');
 const event={id:'meeting',title:'Встреча',date:'2026-09-10',time:'00:30'};
 const payload={ev:[event],settings:{reminderMode:'three-and-hour'}};
 const early=Date.parse('2026-09-09T18:30:30Z'),late=early+7200000;
 const first=dueEvents(payload,'Europe/Moscow',early),second=dueEvents(payload,'Europe/Moscow',late);
 assert.equal(first.length,1);assert.equal(second.length,1);assert.notEqual(first[0].key,second[0].key);
 assert.match(first[0].body,/Через 3 часа/);assert.match(second[0].body,/Через час/);
 assert.equal(second[0].key,dueEvents({ev:[event]},'Europe/Moscow',late)[0].key,'preserve historical delivery key');
 assert.equal(dueEvents({ev:[event]},'Europe/Moscow',early).length,0);
 assert.equal(dueEvents(payload,'Europe/Moscow',early-60000).length,0);
 assert.equal(dueEvents(payload,'Europe/Moscow',early+300000).length,0);
 assert.equal(dueEvents({...payload,ev:[]},'Europe/Moscow',early).length,0);
 assert.equal(dueEvents({...payload,day:{'2026-09-10':{done:['meeting']}}},'Europe/Moscow',early).length,0);
 assert.equal(dueEvents({...payload,ev:[{...event,time:'01:30'}]},'Europe/Moscow',early).length,0);
 const html=fs.readFileSync('index.html','utf8');
 const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://test.invalid/index.html',beforeParse(w){w.matchMedia=()=>({matches:false,addListener(){}});w.scrollTo=()=>{};w.alert=()=>{};}});
 const w=dom.window;
 w.eval("S=blank();S.settings.onboarded=1;renderAll();");
 assert.equal(w.eval('S.settings.reminderMode'),'hour');
 w.eval("document.getElementById('sheet-in').innerHTML=reminderModeField()");
 const select=w.document.querySelector('#reminder-mode');select.value='three-and-hour';select.dispatchEvent(new w.Event('change'));
 assert.equal(w.eval('S.settings.reminderMode'),'three-and-hour');
 w.eval('load();renderAll()');
 assert.equal(w.eval('S.settings.reminderMode'),'three-and-hour');
 assert(w.document.querySelector('#s-more').textContent.includes('за 3 часа и за час'));
 w.eval("setReminderMode('hour')");
 assert.equal(w.eval('S.settings.reminderMode'),'hour');
 dom.window.close();
 console.log('PASS: two reminder times, midnight, stable keys, no early/stale/deleted/done/moved reminders, saved UI selection');
})().catch(e=>{console.error(e);process.exitCode=1});
