import assert from 'node:assert/strict';
import {candidates,reminderText} from './schedule.mjs';
const now=Date.parse('2026-09-13T11:00:00Z'); // 14:00 Moscow; meeting 15:00.
const event={id:'a',date:'2026-09-13',time:'15:00',title:'Стоматолог',address:'Улица 1'};
const payload={ev:[event],day:{},del:[]};
const c=candidates(payload,now)[0];assert.ok(c);assert.match(reminderText(c,now),/Через час/);assert.match(reminderText(c,now),/Улица 1/);
assert.match(reminderText(c,now+120000),/58 мин/);
assert.equal(candidates(payload,now-1).length,0);assert.equal(candidates(payload,now+300000).length,0);
assert.equal(candidates({...payload,ev:[]},now).length,0);
assert.equal(candidates({...payload,del:[{id:'a'}]},now).length,0);
assert.equal(candidates({...payload,day:{'2026-09-13':{done:['a']}}},now).length,0);
assert.equal(candidates({ev:[{...event,time:'16:00'}]},now).length,0);
assert.equal(candidates({ev:[{...event,time:'16:00'}]},now+3600000).length,1);
assert.notEqual(candidates({ev:[{...event,time:'16:00'}]},now+3600000)[0].key,c.key);
assert.equal(candidates({ev:[{...event,time:'25:00'}]},now).length,0);
assert.equal(candidates({ev:[{...event,date:'2026-02-30',repeat:'month'}]},now).length,0);
assert.equal(candidates({ev:[{...event,date:'2026-09-06',repeat:'week'}]},now).length,1);
assert.equal(candidates({ev:[{...event,date:'2026-08-13',repeat:'month'}]},now).length,1);
assert.equal(candidates({ev:[{...event,date:'2025-09-13',repeat:'year'}]},now).length,1);
assert.equal(candidates({ev:[{...event,date:'2026-09-14',time:'00:30'}]},Date.parse('2026-09-13T20:30:00Z')).length,1);
console.log('PASS due window, exact timing, Moscow midnight, move/delete/done, recurrence, invalid dates, address');
