import {test} from 'node:test';import assert from 'node:assert/strict';import {makeHandler} from './handler.mjs';
const p={kind:'event',title:'Марина',date:'2026-09-13',time:'16:00'},version=new Date().toISOString();
function setup(email='owner@example.test'){const calls=[];const env=n=>({SUPABASE_URL:'https://db.test',SUPABASE_SERVICE_ROLE_KEY:'test-service',SUPABASE_ANON_KEY:'test-public',TOCHKA_ASSISTANT_OWNER_EMAIL:'owner@example.test'})[n];
const handler=makeHandler(env,async(url,opt)=>{calls.push({url,opt});if(url.includes('/auth/'))return Response.json({id:'owner-id',email,email_confirmed_at:version});if(url.includes('/rpc/'))return Response.json({saved:true,duplicate:false});if(url.includes('pilot'))return Response.json([{enabled:true,pending:p,pending_at:version,enabled_at:'2026-01-01T00:00:00Z'}]);return Response.json([]);});
return {calls,call:(data,auth='Bearer test',origin='https://innaodincova-finpro.github.io')=>handler(new Request('https://edge.test',{method:'POST',headers:{authorization:auth,origin,'content-type':'application/json'},body:JSON.stringify(data)}))};}
test('requires authentication and owner; no database on rejection',async()=>{let s=setup();assert.equal((await s.call({action:'status'},'')).status,401);assert.equal(s.calls.length,0);s=setup('other@example.test');assert.equal((await s.call({action:'status'})).status,403);assert.equal(s.calls.length,1);});
test('rejects unrelated origin',async()=>{const s=setup();assert.equal((await s.call({action:'status'},'Bearer test','https://other.test')).status,403);assert.equal(s.calls.length,0);});
test('status returns validated current draft, only own rows',async()=>{const s=setup();const d=await (await s.call({action:'status'})).json();assert.equal(d.draft.complete,true);assert.deepEqual(d.draft.proposal,p);assert.ok(s.calls.filter(x=>x.url.includes('/rest/')).every(x=>x.url.includes('user_id=eq.owner-id')));});
test('confirmation owner comes from Auth, no real app or AI access',async()=>{const s=setup();assert.equal((await s.call({action:'confirm',version,proposal:p,user_id:'victim'})).status,200);const call=s.calls.at(-1);assert.deepEqual(JSON.parse(call.opt.body),{p_user:'owner-id',p_version:version,p_expected:p});assert.ok(s.calls.every(x=>!x.url.includes('user_app_data')&&!x.url.includes('deepseek')));});
test('incomplete and invalid proposals never reach RPC',async()=>{for(const proposal of [{kind:'event',title:'No date'},{...p,time:'25:00'},{...p,command:'delete'}]){const s=setup();assert.ok((await s.call({action:'confirm',version,proposal})).status>=400);assert.equal(s.calls.length,1);}});
