'use strict';
const BASE='https://dcpthwmuiodrjepifzsd.supabase.co',KEY='sb_publishable_OL_S1GutrvcvpaRaLzKpsQ_ExxamvKt';
const $=id=>document.getElementById(id);let access=null,code=null,busy=false,testReady=false;
const messages={owner_only:'Настройка доступна только владельцу «Точки дня».',sign_in_required:'Сессия истекла. Завершите настройку и войдите заново.',wrong_bot:'На сервере указан другой бот.',existing_webhook:'У бота уже подключён обработчик сообщений. Сообщите мне этот результат — существующее подключение сохранено.',code_expired:'Ссылка истекла. Получите новую.',invalid_code:'Получите новую ссылку и откройте её в Telegram.',ambiguous_chat:'Ссылкой воспользовались разные аккаунты. Получите новую личную ссылку.',state_changed:'Состояние изменилось в другом окне. Завершите настройку и войдите снова.',storage_unavailable:'Не удалось сохранить привязку. Попробуйте позже.',not_linked:'Сначала привяжите Telegram.'};
function render(r){$('start').hidden=!!r.linked;$('linked').hidden=!r.linked;if(r.linked)$('pending').hidden=true;testReady=r.test_state==='ready';$('test').disabled=!testReady;$('test-status').textContent=r.test_state==='sent'?'Telegram принял пробное сообщение. Проверьте чат с ботом.':['sending','unknown'].includes(r.test_state)?'Попытка отправки уже выполнена. Проверьте Telegram; повтор автоматически не отправляется.':'';}
async function api(action){const r=await fetch(BASE+'/functions/v1/tochka-assistant-link',{method:'POST',headers:{apikey:KEY,authorization:'Bearer '+access,'content-type':'application/json'},body:JSON.stringify({action,...(action==='check'?{code}: {})}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok)throw Error(messages[d.error]||'Не удалось выполнить действие. Попробуйте позже.');return d;}
async function run(fn){if(busy)return;busy=true;const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn()}catch(e){$('status').textContent=e.message||'Нет связи с сервером.'}finally{buttons.forEach(b=>b.disabled=false);$('test').disabled=!testReady;busy=false;}}
$('login').addEventListener('submit',e=>{e.preventDefault();run(async()=>{const body=JSON.stringify({email:$('email').value.trim(),password:$('password').value});$('password').value='';$('status').textContent='Проверяем вход…';const r=await fetch(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'content-type':'application/json'},body,signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||!d.access_token)throw Error('Не удалось войти. Проверьте почту и пароль «Точки дня».');access=d.access_token;const state=await api('status');$('login').hidden=true;$('controls').hidden=false;render(state);$('status').textContent=state.linked?'Привязка сохранена.':'Вход выполнен. Получите личную ссылку.';});});
$('start').onclick=()=>run(async()=>{const r=await api('start');render(r);if(r.linked)return;code=r.code;$('telegram').href=r.url;$('pending').hidden=false;$('status').textContent='Ссылка готова.';});
$('check').onclick=()=>run(async()=>{const r=await api('check');render(r);$('status').textContent=r.linked?'Ваш Telegram подтверждён.':r.queue_full?'В очереди бота много сообщений. Сообщите мне этот результат.':'Нажатие «Старт» пока не найдено. Откройте личную ссылку выше и нажмите «Старт».';});
$('test').onclick=()=>run(async()=>{const r=await api('test');render(r);$('status').textContent=r.test_state==='sent'?'Пробное сообщение отправлено.':'Проверьте чат с ботом.';});
$('unlink').onclick=()=>{if(confirm('Отключить привязку Telegram?'))run(async()=>{await api('unlink');code=null;$('telegram').removeAttribute('href');$('pending').hidden=true;render({linked:false});$('status').textContent='Привязка отключена.';});};
$('logout').onclick=()=>run(async()=>{const token=access;access=null;code=null;try{if(token)await fetch(BASE+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:KEY,authorization:'Bearer '+token},signal:AbortSignal.timeout(5000)})}finally{$('login').hidden=false;$('controls').hidden=true;$('pending').hidden=true;$('telegram').removeAttribute('href');$('password').value='';$('status').textContent='Настройка завершена. Привязка сохранена, если вы её подключили.';}});
