'use strict';
const BASE='https://dcpthwmuiodrjepifzsd.supabase.co',KEY='sb_publishable_OL_S1GutrvcvpaRaLzKpsQ_ExxamvKt';
const $=id=>document.getElementById(id);let token='',busy=false;
const errors={key_missing_or_invalid:'API-ключ DeepSeek не найден или записан с пробелами.',key_rejected:'DeepSeek не принял API-ключ. Проверьте его в настройках сервера.',balance_required:'Нужно пополнить баланс API DeepSeek.',provider_unavailable:'DeepSeek сейчас недоступен. Попробуйте позже.',not_linked:'Сначала привяжите Telegram на странице подключения.',owner_only:'Эта настройка доступна только владельцу «Точки дня».',existing_webhook:'У бота найден другой обработчик. Сообщите об этом в чате настройки.',telegram_unavailable:'Не удалось подключиться к Telegram. Попробуйте позже.',sign_in_required:'Сессия истекла. Обновите страницу и войдите снова.',rollout_not_ready:'Подключение пока не готово.',connection_unavailable:'Не удалось проверить подключение. Попробуйте ещё раз.'};
function showState(data){$('state').textContent=data.enabled?'Помощник включён.':'Помощник выключен.';$('enable').hidden=!!data.enabled;$('disable').hidden=!data.enabled;$('next').hidden=!data.enabled;}
async function api(action){const r=await fetch(BASE+'/functions/v1/tochka-assistant-control',{method:'POST',headers:{apikey:KEY,authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({action}),signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok)throw Error(errors[d.error]||'Не удалось выполнить действие. Попробуйте ещё раз.');return d;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('status').textContent='Проверяем…';try{await fn();}catch(e){$('status').textContent=e.name==='TimeoutError'?'Сервер не успел ответить. Нажмите «Обновить состояние» или повторите вход.':e.message||'Нет соединения.';}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
$('login').addEventListener('submit',e=>{e.preventDefault();run(async()=>{const password=$('password').value;$('password').value='';const r=await fetch(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'content-type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||!d.access_token)throw Error('Не удалось войти. Проверьте почту и пароль «Точки дня».');token=d.access_token;const state=await api('status');$('login').hidden=true;$('controls').hidden=false;showState(state);$('status').textContent='';});});
$('enable').onclick=()=>run(async()=>{showState(await api('enable'));$('status').textContent='DeepSeek и Telegram подключены. Теперь отправьте боту новое сообщение.';});
$('disable').onclick=()=>run(async()=>{showState(await api('disable'));$('status').textContent='Помощник отключён.';});
$('refresh').onclick=()=>run(async()=>{showState(await api('status'));$('status').textContent='Состояние обновлено.';});
$('logout').onclick=()=>run(async()=>{let ok=false;try{const r=await fetch(BASE+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:KEY,authorization:'Bearer '+token},signal:AbortSignal.timeout(8000)});ok=r.ok;}finally{token='';$('controls').hidden=true;$('login').hidden=false;$('status').textContent=ok?'Настройка завершена.':'Страница закрыла сессию в памяти. Сервер не подтвердил выход.';}});
