const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');const {createProposal,applyToSandbox}=require('./proposals');
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'dangerously',url:'https://test.invalid/index.html',beforeParse(w){w.matchMedia=()=>({matches:false,addListener(){}});w.scrollTo=()=>{}}});
const w=dom.window,copy=x=>JSON.parse(JSON.stringify(x)),now=Date.now(),p={id:'test_1',owner:'test_owner',createdAt:now,kind:'notes',record:{date:'2026-09-12',text:'Пробная заметка'}};let count=0;const test=(n,f)=>{f();console.log('PASS '+n);count++};
try{
test('proposal generation and cancellation cannot change base',()=>{const s=w.blank(),before=JSON.stringify(s);createProposal(p);assert.equal(JSON.stringify(s),before)});
test('confirmation and owner required',()=>{for(const opts of [{owner:p.owner},{owner:'other',confirmed:true}])assert.throws(()=>applyToSandbox(w.blank(),p,opts))});
test('expired and future proposals rejected',()=>{for(const createdAt of [now-86400001,now+1])assert.throws(()=>applyToSandbox(w.blank(),{...p,createdAt},{owner:p.owner,confirmed:true,now}))});
test('new records pass current application validation',()=>{for(const proposal of [p,{...p,kind:'ev',record:{date:'2026-09-12',time:'15:00',title:'Встреча'}},{...p,kind:'exp',record:{date:'2026-09-12',sum:850,cat:'Продукты',title:'Покупки'}}])w.validateData(applyToSandbox(w.blank(),proposal,{owner:p.owner,confirmed:true}))});
test('confirmation is immutable and duplicates rejected',()=>{const s=w.blank(),before=JSON.stringify(s);const out=applyToSandbox(s,p,{owner:p.owner,confirmed:true});assert.equal(JSON.stringify(s),before);assert.throws(()=>applyToSandbox(out,p,{owner:p.owner,confirmed:true}));assert.equal(out.notes.length,1)});
test('deleted proposal cannot be resurrected',()=>{const s=w.blank();s.del=[{id:'assistant_test_1',at:new Date().toISOString()}];assert.throws(()=>applyToSandbox(s,p,{owner:p.owner,confirmed:true}))});
test('invalid model output cannot inject actions or settings',()=>{for(const q of [{...p,kind:'delete'},{...p,settings:{}},{...p,record:{...p.record,date:'2026-02-31'}},{...p,record:{...p.record,id:'replace_existing'}},{...p,kind:'exp',record:{date:'2026-09-12',sum:true,cat:'x',title:'x'}}])assert.throws(()=>createProposal(q))});
test('simultaneous phone edit and assistant addition survive both merge orders',()=>{const b=w.blank();b.notes=[{id:'phone',date:'2026-09-12',text:'old'}];const l=copy(b);l.notes[0].text='phone edit';const r=applyToSandbox(b,p,{owner:p.owner,confirmed:true});for(const [a,z] of [[l,r],[r,l]]){const m=w.mergeThree(b,a,z);assert.equal(m.notes.length,2);assert.equal(m.notes.find(n=>n.id==='phone').text,'phone edit');assert.equal(m.notes.find(n=>n.id==='assistant_test_1').text,p.record.text)}});
test('phone deletion preserved alongside addition',()=>{const b=w.blank();b.notes=[{id:'old',date:'2026-09-12',text:'remove'}];const l=copy(b);l.notes=[];l.del=[{id:'old',at:new Date().toISOString()}];const r=applyToSandbox(b,p,{owner:p.owner,confirmed:true}),m=w.mergeThree(b,l,r);assert.equal(m.notes.length,1);assert.equal(m.notes[0].id,'assistant_test_1')});
test('UI escapes text and has no network or persistent storage calls',()=>{for(const file of ['ui.js','proposals.js'])assert.doesNotMatch(fs.readFileSync('assistant-lab/'+file,'utf8'),/\b(fetch|XMLHttpRequest|WebSocket|localStorage|sessionStorage|indexedDB|innerHTML)\b/);assert.match(fs.readFileSync('assistant-lab/index.html','utf8'),/connect-src 'none'/)});
console.log(count+' assistant sandbox scenarios passed; real Telegram and cloud not connected.');
}finally{dom.window.close()}
