import {test} from 'node:test';import assert from 'node:assert/strict';import {makeHandler} from './handler.mjs';import {blank,mergeThree} from './core.mjs';import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';
const proposal={kind:'event',title:'Марина',date:'2026-09-13',time:'16:00'},version='2026-09-12T18:00:00+00:00';
function fixture(email='owner@example.test'){
 let row={source_version:version,proposal,calendar_revision:0,calendar_event:null};const calls=[];
 const env=n=>({SUPABASE_URL:'https://db.test',SUPABASE_SERVICE_ROLE_KEY:'test',SUPABASE_ANON_KEY:'public',TOCHKA_ASSISTANT_OWNER_EMAIL:'owner@example.test'})[n];
 const h=makeHandler(env,async(url,opt)=>{calls.push(url);if(url.includes('/auth/'))return Response.json({id:'owner',email,email_confirmed_at:version});
 assert.ok(url.includes('user_id=eq.owner'));assert.ok(url.includes('tochka_assistant_sandbox'));
 if(opt.method==='PATCH'){if(!url.includes('calendar_revision=eq.'+row.calendar_revision))return Response.json([]);row={...row,...JSON.parse(opt.body)};}
 return Response.json([row]);});
 return {calls,call:async data=>{const r=await h(new Request('https://edge.test',{method:'POST',headers:{authorization:'Bearer test','content-type':'application/json'},body:JSON.stringify(data)}));return {status:r.status,...await r.json()};}};
}
test('repeat and concurrent import are idempotent; original draft untouched',async()=>{const f=fixture();const results=await Promise.all([f.call({action:'import',version}),f.call({action:'import',version})]);assert.ok(results.some(x=>x.record.calendar_revision===1));const d=await f.call({action:'import',version});assert.equal(d.duplicate,true);assert.equal(d.record.calendar_revision,1);assert.deepEqual(d.record.proposal,proposal);});
test('edit and stale revision; no working data route',async()=>{const f=fixture();await f.call({action:'import',version});const d=await f.call({action:'edit',version,revision:1,proposal:{...proposal,time:'17:00'}});assert.equal(d.record.calendar_event.time,'17:00');const stale=await f.call({action:'edit',version,revision:1,proposal});assert.equal(stale.status,409);assert.equal(stale.record.calendar_event.time,'17:00');assert.ok(f.calls.every(x=>!x.includes('user_app_data')));});
test('non-owner blocked before database',async()=>{const f=fixture('someone@example.test');assert.equal((await f.call({action:'list'})).status,403);assert.equal(f.calls.length,1);});
test('invalid date/time or missing fields rejected',async()=>{for(const p of [{...proposal,time:'25:00'},{...proposal,date:'2026-02-31'},{kind:'note',title:'note'},{kind:'event',title:'missing'}]){const f=fixture();await f.call({action:'import',version});assert.equal((await f.call({action:'edit',version,revision:1,proposal:p})).status,400);}});
test('same app merge: independent changes survive, same-field conflict stops, no duplicate',()=>{const b={...blank(),ev:[{id:'one',title:'Марина',date:'2026-09-13',time:'16:00',place:''}]},l=structuredClone(b),r=structuredClone(b);l.ev[0].time='17:00';r.ev[0].place='Кафе';const m=mergeThree(b,l,r);assert.equal(m.ev.length,1);assert.equal(m.ev[0].time,'17:00');assert.equal(m.ev[0].place,'Кафе');r.ev[0].time='18:00';assert.throws(()=>mergeThree(b,l,r),e=>e.conflict===true);});
test('SQL revision compare-and-swap and client permissions',async()=>{const db=new PGlite();await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create table tochka_assistant_sandbox(user_id uuid,source_version timestamptz,proposal jsonb,primary key(user_id,source_version));alter table tochka_assistant_sandbox enable row level security;revoke all on tochka_assistant_sandbox from public,anon,authenticated;");await db.exec(fs.readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));const uid='00000000-0000-0000-0000-000000000001';await db.query('insert into tochka_assistant_sandbox(user_id,source_version,proposal) values($1,$2,$3)',[uid,version,proposal]);const update=()=>db.query("update tochka_assistant_sandbox set calendar_event=$1,calendar_revision=1 where user_id=$2 and source_version=$3 and calendar_revision=0 returning calendar_revision",[proposal,uid,version]);assert.equal((await update()).rows.length,1);assert.equal((await update()).rows.length,0);for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(db.query('select calendar_event from tochka_assistant_sandbox'));await assert.rejects(update());await db.exec('reset role');}await db.close();});
