import {JSDOM} from 'jsdom';import fs from 'node:fs';import assert from 'node:assert/strict';import {blank,mergeThree} from './core.mjs';
const version='2026-09-12T18:00:00Z';let row={source_version:version,proposal:{kind:'event',title:'Марина',date:'2026-09-13',time:'16:00'},calendar_revision:0,calendar_event:null};
const wait=async()=>{for(let i=0;i<30;i++)await new Promise(r=>setImmediate(r));};
function tab(){const w=new JSDOM(fs.readFileSync(new URL('./web/calendar.html',import.meta.url),'utf8'),{url:'https://innaodincova-finpro.github.io/tochka-assistant/calendar.html',runScripts:'outside-only'}).window;const $=id=>w.document.getElementById(id);
w.AbortSignal=AbortSignal;w.structuredClone=structuredClone;w.blank=blank;w.mergeThree=mergeThree;
w.fetch=async(url,opt)=>{if(url.includes('/auth/'))return Response.json({access_token:'fake'});const d=JSON.parse(opt.body);if(d.action==='list')return Response.json({records:[row]});if(d.action==='import'){row={...row,calendar_revision:1,calendar_event:{id:'one',title:'Марина',date:'2026-09-13',time:'16:00',place:'',repeat:'none'}};return Response.json({record:row});}if(d.revision!==row.calendar_revision)return Response.json({error:'conflict',record:row},{status:409});row={...row,calendar_revision:row.calendar_revision+1,calendar_event:{...row.calendar_event,title:d.proposal.title,date:d.proposal.date,time:d.proposal.time,place:d.proposal.place}};return Response.json({record:row});};
w.eval(fs.readFileSync(new URL('./web/calendar.js',import.meta.url),'utf8').replace("import {blank,mergeThree} from './calendar-core.mjs';",''));
return {w,$,async login(){$('email').value='owner@example.test';$('password').value='password';$('loginform').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait();},async edit(){ $('month').value='2026-09';$('month').dispatchEvent(new w.Event('change'));[...$('grid').querySelectorAll('button')].find(b=>b.textContent.startsWith('13')).click();$('events').querySelector('button').click();},async save(){ $('editform').dispatchEvent(new w.Event('submit',{cancelable:true}));await wait();}};}
const a=tab();await a.login();a.$('sources').querySelector('button').click();await wait();assert.match(a.$('events').textContent,/16:00.*Марина/);assert.equal(a.$('sources').querySelectorAll('button').length,0);
const b=tab();await b.login();await a.edit();await b.edit();a.$('time').value='17:00';await a.save();b.$('place').value='Кафе';await b.save();assert.equal(row.calendar_event.time,'17:00');assert.equal(row.calendar_event.place,'Кафе');assert.equal(b.$('editor').hidden,true);
a.$('refresh').click();await wait();await a.edit();await b.edit();a.$('time').value='18:00';await a.save();b.$('time').value='19:00';await b.save();assert.equal(row.calendar_event.time,'18:00');assert.equal(b.$('conflict').hidden,false);assert.equal(b.$('time').value,'19:00');assert.match(b.$('status').textContent,/перезапись остановлена/);
a.w.close();b.w.close();console.log('UI: import, calendar day, edit, two-tab independent merge, same-field conflict passed (mock API).');
